@startuml Lab01_Task7_Schema2

start

partition Array {
	:==**Positive Lookbehind**==
                 `{`;
		partition ArrayElement {
			repeat
                partition Number {
                    split
                        partition Integer {
                            split
                                :'-';
                            split again
                                :'+';
                            split again
                            end split

                            split
                                :'0';
                            split again
                                :==**One of**==\n '1' - '9';
                                split
                                    while (==**One of**==\n '0' - '9')
                                    endwhile
                                split again
                                end split
                            end split
                        }
                        
                    split again
                        partition Partition {
                            :'.';
                            while (==**One of**==\n '0' - '9')
                            endwhile
                        }
                            
                    split again
                        partition Float {
                            split
                                :'-';
                            split again
                                :'+';
                            split again
                            end split

                            split
                                :'0';
                            split again
                                :==**One of**==\n '1' - '9';
                                split
                                    while (==**One of**==\n '0' - '9')
                                    endwhile
                                split again
                                end split
                            end split

                            :'.';
                            while (==**One of**==\n '0' - '9')
                            endwhile
                        }
                            
                    end split

                    split
                        partition Exponent {
                            split
                                :'e';
                            split again
                                :'E';
                            end split

                            split
                                :'-';
                            split again
                                :'+';
                            split again
                            end split

                            while (==**One of**==\n '0' - '9')
                            endwhile
                        }
                    split again
                    end split

                    split
                        partition Suffix {
                            split
                                :'f';
                            split again
                                :'F';
                            split again
                                :'l';
                            split again
                                :'L';
                            end split
                        }
                    split again
                    end split
                }
			repeat while (Lookahead) is (';')
			->'}';
		}
	:==**Positive Lookahead**==
                `}`;

}

stop

@enduml