name: build

on:
  push:
    tags:
      - lab*
    branches:
      - lab*
      - main
  pull_request:

env:
  antlr: antlr-4.10.1-complete.jar
  antlr_ver: 4.10.1

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: '[ANTLR4] Install'
        run: |
          curl -O https://www.antlr.org/download/$antlr

      - name: '[ANTLR4] Build Go runtime'
        run: |
          go get github.com/antlr/antlr4/runtime/Go/antlr@4.10.1
          java -jar $antlr -Dlanguage=Go build/grammar/RustLexer.g4
